filter_type = ("lpf_1p", "hpf_1p", "lpf_2p", "hpf_2p", "bpf_2p", "brf_2p")
off_modes = ("fast", "normal")
loop_modes = ("None", "no_loop", "one_shot", "loop_continuous", "loop_sustain")
loop_directions = ("forward", "reverse")
loop_types = ("forward", "backward", "alternate")
trigger_modes = ("attack", "release", "first", "legato", "release_key")
lfo_waves = ("triangle", "sine", "75% pulse", "square", "25% pulse", "12.5% pulse", "saw going up", "saw going down")
wavetables = ("Sine", "Triangle", "Square", "Saw", "Noise", "Sample")
wave_modes = ("Normal/RM", "PM", "FM")
# drums
xg_list_1 =   ("13 Surdo Mute",
               "14 Surdo Open",
               "15 Hi Q",
               "16 Whip Slap",
               "17 Scratch H",
               "18 Scratch L",
               "19 Finger Snap",
               "20 Click Noise",
               "21 Metronome Click",
               "22 Metronome Bell]",
               "23 Seq Click L",
               "24 Seq Click H",
               "25 Brush Tap",
               "26 Brush Swirl",
               "27 Brush Slap",
               "28 Brush Tap Swirl",
               "29 Snare Roll",
               "30 Castanet",
               "31 Snare Soft",
               "32 Sticks",
               "33 Kick Soft",
               "34 Open Rim Shot")

gs_list_1 =  ("22 MC-500 Beep 1",
              "23 MC-500 Beep 2",
              "24 Concert SD",
              "25 Snare Roll",
              "26 Finger Snap 2",
              "27 High Q",
              "28 Slap",
              "29 Scratch Push",
              "30 Scratch Pull",
              "31 Sticks",
              "32 Square Click",
              "33 Metronome Click",
              "34 Metronome Bell")

gm_list_drums =  ("35 Kick Drum 2",
                  "36 Kick Drum 1",
                  "37 Side Stick",
                  "38 Snare Drum 1",
                  "40 Snare Drum 2",
                  "41 Low Tom 1",
                  "43 Low Tom 2",
                  "45 Mid Tom 1",
                  "47 Mid Tom 2",
                  "48 High Tom 1",
                  "50 High Tom 2")

gm_list_cym =  ("42 Hi-hat Closed",
                "44 Hi-hat Pedal",
                "46 Hi-hat Open",
                "49 Cymbal Crash 1",
                "51 Cymbal Ride 1",
                "52 Cymbal Chinese",
                "53 Cymbal Ride Bell",
                "55 Cymbal Splash",
                "57 Cymbal Crash 2",
                "59 Cymbal Ride 2")

gm_list_perc = ("39 Hand Clap",
                "54 Tambourine",
                "56 Cowbell",
                "58 Vibra-slap",
                "60 High Bongo",
                "61 Low Bongo",
                "62 Mute High Conga",
                "63 Open High Conga",
                "64 Low Conga",
                "65 High Timbale",
                "66 Low Timbale",
                "67 High Agogo",
                "68 Low Agogo",
                "69 Cabasa",
                "70 Maracas",
                "71 Short Hi Whistle",
                "72 Long Low Whistle",
                "73 Short Guiro",
                "74 Long Guiro",
                "75 Claves",
                "76 High Wood Block",
                "77 Low Wood Block",
                "78 Mute Cuica",
                "79 Open Cuica",
                "80 Mute Triangle",
                "81 Open Triangle",
                "82 Shaker",
                "83 Jingle Bell",
                "84 Bell Tree",
                "85 Castanets",
                "86 Mute Surdo",
                "87 Open Surdo",
                "88 Applause 2")

cc_list = ("0 Bank Select (MSB)",
           "1 Modulation Wheel",
           "2 Breath controller",
           "3",
           "4 Foot Pedal (MSB)",
           "5 Portamento Time (MSB)",
           "6 Data Entry (MSB)",
           "7 Volume (MSB)",
           "8 Balance (MSB",
           "9",
           "10 Pan position (MSB)",
           "11 Expression (MSB)",
           "12 Effect Control 1 (MSB)",
           "13 Effect Control 2 (MSB)",
           "14",
           "15",
           "16 General Purpose",
           "17 General Purpose",
           "18 General Purpose",
           "19 General Purpose",
           "20",
           "21",
           "22",
           "23",
           "24",
           "25",
           "26",
           "27",
           "28",
           "29",
           "30",
           "31",
           "32 Bank Select (LSB)",
           "33 Modulation Wheel",
           "34 Breath controller",
           "35",
           "36 Foot Pedal (LSB)",
           "37 Portamento Time (LSB)",
           "38 Data Entry (LSB)",
           "39 Volume (LSB)",
           "40 Balance (LSB",
           "41",
           "42 Pan position (LSB)",
           "43 Expression (LSB)",
           "44 Effect Control 1 (LSB)",
           "45 Effect Control 2 (LSB)",
           "46",
           "47",
           "48",
           "49",
           "50",
           "51",
           "52",
           "53",
           "54",
           "55",
           "56",
           "57",
           "58",
           "59",
           "60",
           "61",
           "62",
           "63",
           "64 Hold Pedal",
           "65 Portamento",
           "66 Sostenuto Pedal",
           "67 Soft Pedal",
           "68 Legato Pedal",
           "69 Hold 2 Pedal",
           "70 Sound Variation",
           "71 Resonance (Timbre)",
           "72 Amp Env Release",
           "73 Amp Env Attack",
           "74 Cutoff (Brightness)",
           "75 Sound Controller 6",
           "76 Sound Controller 7",
           "77 Sound Controller 8",
           "78 Sound Controller 9",
           "79 Sound Controller 10",
           "80 General Purpose (on/off)",
           "81 General Purpose (on/off)",
           "82 General Purpose (on/off)",
           "83 General Purpose (on/off)",
           "84",
           "85",
           "86",
           "87",
           "88",
           "89",
           "90",
           "91 Effect 1 (Reverb)",
           "92 Effect 2 (Tremelo)",
           "93 Effect 3 (Chorus)",
           "94 Effect 4 (Detuning)",
           "95 Effect 5 (Phaser)",
           "96 Data Bound Increment (+1)",
           "97 Data Bound Decrement (-1)",
           "98 NRPN LSB",
           "99 NRPN MSB",
           "100 RPN LSB",
           "101 RPN MSB",
           "102",
           "103",
           "104",
           "105",
           "106",
           "107",
           "108",
           "109",
           "110",
           "111",
           "112",
           "113",
           "114",
           "115",
           "116",
           "117",
           "118",
           "119",
           "120 All Sound Off",
           "121 All Controllers Off",
           "122 Local Keyboard (on/off)",
           "123 All Notes Off",
           "124 Omni Mode Off",
           "125 Omni Mode On",
           "126 Mono Operation",
           "127 Poly Mode",

           "128 Pitch Bend",
           "129 Channel Aftertouch",
           "130 Polyphonic Aftertouch",
           "131 Note On Velocity",
           "132 Note Off Velocity",
           "133 Keyboard Note Number",
           "134 Keyboard Note Gate",
           "135 Unipolar Random",
           "136 Bipolar Random",
           "137 Alternate")
